# Generated by Django 2.2.dev20180608160017 on 2018-06-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_key',
            new_name='billing_address_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_key',
            new_name='customer_id',
        ),
    ]
