# Generated by Django 2.2.dev20180608160017 on 2018-06-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0003_auto_20180614_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='Item name', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
