# Generated by Django 2.2.dev20180608160017 on 2018-06-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0005_auto_20180614_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ItemCategory',
        ),
    ]
