# Generated by Django 2.2.dev20180608160017 on 2018-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0006_auto_20180614_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='billing_address_id',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='address_key',
            new_name='address_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_id',
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='Unbranded', max_length=200, null=True),
        ),
    ]
