# Generated by Django 2.2.dev20180608160017 on 2018-06-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0007_auto_20180616_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address_id',
        ),
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oms.Customer'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
