# Generated by Django 2.2.dev20180608160017 on 2018-06-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0008_auto_20180616_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CONFIRMED', 'CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], default='CREATED', max_length=200),
        ),
    ]
